backend:
  name: github
  repo: wanliu530/lenamirror
  branch: main
  base_url: https://lenamirror.pages.dev
media_folder: assets/upload
public_folder: /assets/upload
collections:
  - name: journal
    label: Journal 随笔
    folder: content/journal
    create: true
    delete: true
    preview_path: /journal.html 
    fields:
      - label: "标题"
        name: title
        widget: string
      - label: "发布日期"
        name: date
        widget: datetime
      - label: "正文内容"
        name: body
        widget: markdown
  - name: gallery
    label: Gallery 相册
    folder: content/gallery
    create: true
    delete: true
    preview_path: /gallery.html 
    fields:
      - label: 照片标题/描述
        name: title
        widget: string
      - label: 上传日期
        name: date
        widget: datetime
      - label: 相册分类
        name: album_category
        widget: select
        options:
          - Daily Life
          - Portrait
          - Liu Mi
      - label: 照片图片
        name: image
        widget: image